package autocode

type ServiceGroup struct {
	// Code generated by raptor/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	KeyService
	AssetService
	ProductService
	// Code generated by raptor/server End; DO NOT EDIT.
}
