package autocode

type ApiGroup struct {
	// Code generated by raptor/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	KeyApi
	AssetApi
	ProductApi
	// Code generated by raptor/server End; DO NOT EDIT.
}
