package autocode

type RouterGroup struct {
	// Code generated by raptor/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	KeyRouter
	AssetRouter
	ProductRouter
	// Code generated by raptor/server End; DO NOT EDIT.
}
